### PR TITLE
update adding KDE SDK support for Global Menu and KDE Themes

### PR DESCRIPTION
**Pull request by JosepHyv**
Can you check my PR for support to KDE?

### CODE REVIEW

**Comment by JosepHyv** [comment]
Can you check my PR for support to KDE?

**Comment by Zeller1** [comment]
Yo, thanks so much! I have been trying to get Packet Tracer working right on Kali for a while then I found this and it worked perfectly.

**Comment by leleobhz** [comment]
Hello @JosepHyv 

2 cent's here: I failed a bit trying to build a native KDE/QT flatpak (https://github.com/leleobhz/com.cisco.PacketTracer/blob/feature-use-flatpak-kde-qt/com.cisco.PacketTracer.yml). Image brings some SEGFAULTs at `libQt5XcbQpa.so.5.15.10` for reasons I still don't know why (And PT claims for a startup script I was unable to track it).

That said, 2 points here:

1) I used SDK/Platform 5.15-22.08 instead 5.15-21.08. Using 21.08 of any platform makes Flapak/Warehouse tag image as EOL. I tested a single Freedesktop update and it ran very well. Maybe this is appliable to KDE/QT platform?

2) I suggest do not fork to a .kde.yml since PT is a QT application and a strict Freedesktop SDK/Platform will not have any integrations that makes PT a bit more usable. Even on gnome. I did a branch ( https://github.com/leleobhz/com.cisco.PacketTracer/blob/feature-use-flatpak-kde-qt-with-cisco-static-qt-libs/com.cisco.PacketTracer.yml ) to validate this setup.

I made some new work, but since you started it first, it's fair to point a comment instead just pass a new concurrent PR.

What do you think about?

Thanks!

**Comment by losuler** [comment]
Thank you @JosepHyv and @leleobhz for all your work on this. Sorry I didn't get around to it until now. I was hesitant initially to require the KDE platform, but seems like @leleobhz has done a bit more work testing this, so I'll trust them on this one. As it'd be a bit of pain maintaining both, I'd rather not have a separate manifest just for KDE. Because of this, and the aforementioned errors, I'll close this in favor of https://github.com/losuler/com.cisco.PacketTracer/pull/19.

**Pull request closed without merging**
